### ISSUE TITLE
DeprecationWarning: inkex.deprecated.main.transform_mul

### ISSUE THREAD

**Issue by imabot2** [Klowner/inkscape-applytransforms#58] opened 2022-10-01 17:12 UTC
I try the extension on Inkscape 1.2.1, I've got the following error. 
```
applytransform.py:60: DeprecationWarning: inkex.deprecated.main.transform_mul -> Use @ operator instead
  transf = Transform(transf) * Transform(node.get("transform", None))
```

I found the line in the Python script, but I'm not sure how to update the code.

**Comment by Klowner** [comment] 2022-10-01 17:32
That's not an error, just a deprecation warning. 

Python now uses an `@` for matrix multiplication.

**Comment by imabot2** [comment] 2022-10-01 18:03
Thank you, I try this, but it didn't solve my problem

 transf = Transform(transf) @ Transform(node.get("transform", None))

**Comment by Klowner** [comment] 2022-10-01 18:13
Duplicate of #55

**Closed** 2022-10-01 18:13 UTC
